### ISSUE TITLE
[Blocker] [feature/navBar] 내비게이션 바 close 여부에 반응한 section component 구현

### ISSUE THREAD

**Issue by hjkdw95** [hjkdw95/trustVerse-admin-page-project#25]
<img width="326" alt="스크린샷 2021-10-21 오후 3 33 35" src="https://user-images.githubusercontent.com/76423949/138223896-62e57c41-a4f0-49e2-b34c-c17117fe4ab2.png">

component map
```
|-- NavBar
     |-- AccordianBar
     |-- StatusBar
|-- TAMS / Jupiter
```

위와 같은 상태로 navBar 여닫는 status는 navBar component 안에 만들었습니다.
TAMS/Jupiter의 padding/margin도 관리하려면 상태관리를 최상단인 `Routes.js`에서 진행해야되는데, 보통 이런경우 redux나 mobx 등 상태관리 라이브러리를 사용하여 `Routes.js`에 state를 이식하는 것으로 확인되었습니다.

<질문>
1. 상태관리 라이브러리 사용 없이 위의 navBar의 state를 TAMS나 Jupiter로 이식할 수 있을까요?
2. 아니면 mobX를 적용해볼까 하는데 괜찮으실까요?

**Comment by ssxst31** [comment]
저도 검색해 보니 상태 관리를 써야 할 거 같다고 판단되는데 mobX도 좋을 거 같고 navBar의 상태만 전역으로 관리하신다면 Context API라는 리액트 내장 라이브러리도 있던데 어떠신가요?

**Comment by hjkdw95** [comment]
context API 사용하여 구현 성공하였습니다
